"""empty message

Revision ID: 09dbb4e92fab
Revises: e199d16063f4
Create Date: 2016-06-16 09:26:53.630653

"""

# revision identifiers, used by Alembic.
revision = '09dbb4e92fab'
down_revision = 'e199d16063f4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('validation_code', sa.Unicode(length=256), nullable=False, server_default=''))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'validation_code')
    ### end Alembic commands ###
