"""empty message

Revision ID: 310fd91d09b2
Revises: 9e0d6cf356f9
Create Date: 2016-07-20 19:51:47.478739

"""

# revision identifiers, used by Alembic.
revision = '310fd91d09b2'
down_revision = '9e0d6cf356f9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Unicode(length=256), nullable=False),
    sa.Column('content', sa.UnicodeText(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    ### end Alembic commands ###
