"""empty message

Revision ID: 3a54cee4786d
Revises: 0fa97e80afd1
Create Date: 2016-05-12 11:12:00.599658

"""

# revision identifiers, used by Alembic.
revision = '3a54cee4786d'
down_revision = '0fa97e80afd1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    pass
    ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('builds', sa.Column('status', sa.Unicode(length=256), nullable=False, server_default="''"))
    ### end Alembic commands ###


def downgrade():
    pass
    ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('builds', 'status')
    ### end Alembic commands ###
