"""empty message

Revision ID: e199d16063f4
Revises: 3a54cee4786d
Create Date: 2016-05-12 12:05:43.286093

"""

# revision identifiers, used by Alembic.
revision = 'e199d16063f4'
down_revision = '3a54cee4786d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tags', sa.UnicodeText(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    ### end Alembic commands ###
